export const herbs = [
  {
    slug: "ashwagandha",
    name: "Ashwagandha",
    botanical: "Withania somnifera",
    verdict: "PROVEN",
    studies: 15,
    icon: "🌿",
    tagline: "Stress, cortisol, endurance — 15+ RCTs confirm real effects",
    summary: "Ashwagandha is one of the most well-studied Ayurvedic herbs. Multiple randomized controlled trials confirm its effects on stress reduction, cortisol levels, and physical performance.",
    keywords: ["ashwagandha benefits", "ashwagandha side effects", "himalaya ashwagandha", "ashwagandha benefits in hindi"],
  },
  {
    slug: "turmeric",
    name: "Turmeric / Curcumin",
    botanical: "Curcuma longa",
    verdict: "PROVEN",
    studies: 20,
    icon: "🟡",
    tagline: "Anti-inflammatory powerhouse — but bioavailability is the catch",
    summary: "Curcumin, the active compound in turmeric, has extensive clinical evidence for anti-inflammatory effects. However, its poor bioavailability without piperine is a critical factor most articles ignore.",
    keywords: ["turmeric benefits", "curcumin vs turmeric", "haldi benefits"],
  },
  {
    slug: "boswellia",
    name: "Boswellia",
    botanical: "Boswellia serrata",
    verdict: "PROVEN",
    studies: 8,
    icon: "🌳",
    tagline: "Comparable to NSAIDs for arthritis — fewer side effects",
    summary: "Boswellia serrata has clinical evidence showing anti-inflammatory effects comparable to NSAIDs in arthritis, with significantly fewer gastrointestinal side effects.",
    keywords: ["boswellia benefits", "shallaki benefits", "boswellia vs ibuprofen"],
  },
  {
    slug: "triphala",
    name: "Triphala",
    botanical: "Emblica officinalis + Terminalia bellirica + Terminalia chebula",
    verdict: "PROMISING",
    studies: 6,
    icon: "🫐",
    tagline: "Gut health and antioxidant effects — more large trials needed",
    summary: "Triphala shows promising results for gut microbiota improvement and constipation relief in clinical trials, with emerging antioxidant research in preclinical studies.",
    keywords: ["triphala benefits", "triphala for digestion", "triphala side effects"],
  },
  {
    slug: "brahmi",
    name: "Brahmi",
    botanical: "Bacopa monnieri",
    verdict: "PROMISING",
    studies: 7,
    icon: "🧠",
    tagline: "Memory and cognition gains in 12-week studies",
    summary: "Brahmi (Bacopa monnieri) has multiple clinical trials showing improvements in memory and cognitive function over 12-week study periods, though dose standardization remains inconsistent.",
    keywords: ["brahmi benefits", "bacopa monnieri", "brahmi for memory"],
  },
  {
    slug: "shatavari",
    name: "Shatavari",
    botanical: "Asparagus racemosus",
    verdict: "PROMISING",
    studies: 4,
    icon: "🌸",
    tagline: "Women's health — emerging but limited clinical evidence",
    summary: "Shatavari has traditional use for women's health and hormonal balance, with some clinical evidence for lactation support. PCOS-specific research is emerging but limited.",
    keywords: ["shatavari benefits", "shatavari for women", "shatavari pcos"],
  },
  {
    slug: "shilajit-evidence-scorecard",
    name: "Shilajit",
    botanical: "Asphaltum / Mineral pitch",
    verdict: "LIMITED",
    studies: 4,
    icon: "🏔️",
    tagline: "Massive popularity, limited clinical trials — the gap is the story",
    summary: "Shilajit is one of India's most popular supplements, but the clinical evidence base is surprisingly thin. Very few quality human RCTs exist despite enormous traditional use.",
    keywords: ["shilajit benefits", "shilajit real vs fake", "kapiva shilajit"],
  },
  {
    slug: "giloy",
    name: "Giloy",
    botanical: "Tinospora cordifolia",
    verdict: "LIMITED",
    studies: 3,
    icon: "🌱",
    tagline: "Government promoted it during COVID — what does the evidence actually show?",
    summary: "Giloy was heavily promoted during COVID as an immunity booster. The published clinical evidence is limited, and liver injury reports have emerged as a safety signal.",
    keywords: ["giloy benefits", "giloy benefits for female", "giloy side effects"],
  },
  {
    slug: "tulsi",
    name: "Tulsi (Holy Basil)",
    botanical: "Ocimum tenuiflorum / Ocimum sanctum",
    verdict: "PROMISING",
    studies: 5,
    icon: "🌿",
    tagline: "Documented compounds, adaptogenic potential — needs larger human trials",
    summary: "Tulsi contains well-documented compounds including eugenol, ursolic acid, and rosmarinic acid. Adaptogenic and antimicrobial properties are supported by preclinical data, but large-scale human RCTs are limited.",
    keywords: ["tulsi benefits", "tulsi benefits for skin", "ram tulsi benefits"],
  },
  {
    slug: "neem",
    name: "Neem",
    botanical: "Azadirachta indica",
    verdict: "PROMISING",
    studies: 4,
    icon: "🍃",
    tagline: "Antimicrobial properties documented — limited large-scale human data",
    summary: "Neem has extensive traditional use and documented antimicrobial properties. However, most claims are supported by preclinical studies rather than large-scale human clinical trials.",
    keywords: ["neem benefits", "neem benefits for skin", "neem benefits for hair"],
  },
  {
    slug: "amla",
    name: "Amla",
    botanical: "Phyllanthus emblica / Emblica officinalis",
    verdict: "PROMISING",
    studies: 5,
    icon: "🫒",
    tagline: "Vitamin C powerhouse — antioxidant and lipid research emerging",
    summary: "Amla is one of the richest natural sources of Vitamin C and a key ingredient in both Triphala and Chyawanprash. Emerging research covers antioxidant effects and lipid modulation.",
    keywords: ["amla benefits", "amla for hair", "amla vitamin c"],
  },
];

export function getHerbBySlug(slug) {
  return herbs.find(h => h.slug === slug);
}

export function getVerdictClass(verdict) {
  switch (verdict) {
    case "PROVEN": return "verdict-proven";
    case "PROMISING": return "verdict-promising";
    case "LIMITED": return "verdict-limited";
    default: return "";
  }
}
